name: Terraform CI/CD

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
  push:
    branches:
      - main
    paths:
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Configure AWS Credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: infra/terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/terraform

      - name: Terraform Plan (PR)
        if: github.event_name == 'pull_request'
        run: terraform plan
        working-directory: infra/terraform

      - name: Terraform Apply (Merge)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        working-directory: infra/terraform